name: imscaler
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  flutter_riverpod: ^2.4.5
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.6.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  image_cropper: ^9.1.0
  permission_handler: ^11.0.0
  image: ^4.0.17
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  assets:
    - assets/wallpaper.webp
    - assets/app_icon.png
    - assets/models/upscaler.tflite

  uses-material-design: true


